name: Test on push

on:
  push

jobs:
  setup:
    name: 'â–¶ï¸ setup actions'
    uses: ./.github/workflows/setup.yml

  test:
    name: 'â–¶ï¸ test actions'
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: 'ğŸ§« Run tests'
        run: npm run test --if-present
